# Generated by Django 5.2.8 on 2025-11-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0004_alter_pret_membre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="don",
            name="donateur",
        ),
        migrations.RemoveField(
            model_name="don",
            name="enregistre_par",
        ),
        migrations.RemoveField(
            model_name="don",
            name="tontine",
        ),
        migrations.RemoveField(
            model_name="pret",
            name="approuve_par",
        ),
        migrations.RemoveField(
            model_name="pret",
            name="membre",
        ),
        migrations.RemoveField(
            model_name="pret",
            name="tontine",
        ),
        migrations.RemoveField(
            model_name="remboursement",
            name="pret",
        ),
        migrations.RemoveField(
            model_name="remboursement",
            name="enregistre_par",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="est_admin",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="est_tresorier",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.DeleteModel(
            name="Cotisation",
        ),
        migrations.DeleteModel(
            name="Don",
        ),
        migrations.DeleteModel(
            name="Pret",
        ),
        migrations.DeleteModel(
            name="Remboursement",
        ),
    ]
